name: "tau-crystal-action"
description: "Receipt-first, Merkle-rooted attestation via pure bash (Lean optional via elan)."
author: "towre676-cloud"
branding:
  icon: shield
  color: purple

inputs:
  working-directory:
    description: "Path to verify"
    required: false
    default: "."
  install-elan:
    description: "Install Lean toolchain with elan"
    required: false
    default: "true"

outputs:
  verifier:
    description: "Absolute path to bundled verifier script"
    value: ${{ steps.expose.outputs.verifier }}
  receipt:
    description: "Latest receipt JSON path"
    value: ${{ steps.outs.outputs.receipt }}
  chain-head:
    description: "CHAIN head (sha256)"
    value: ${{ steps.outs.outputs.head }}
  merkle-root:
    description: "Manifest merkle root"
    value: ${{ steps.outs.outputs.root }}

runs:
  using: "composite"
  steps:
    - id: expose
      shell: bash
      run: |
        set -euo pipefail
        v="$GITHUB_ACTION_PATH/verify/verify-receipt.sh"
        chmod +x "$v" || true
        echo "verifier=$v" >> "$GITHUB_OUTPUT"

    - name: Install elan (optional)
      if: ${{ inputs.install-elan == 'true' }}
      shell: bash
      run: |
        set +H; umask 022
        curl -sSfL https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh | sh -s -- -y
        echo "$HOME/.elan/bin" >> "$GITHUB_PATH"

    - name: Verify with tau-crystal
      shell: bash
      env:
        ACTION_DIR: ${{ github.action_path }}
      working-directory: ${{ inputs.working-directory }}
      run: |
        set +H; umask 022
        if [ -x "$ACTION_DIR/scripts/tau_verify.sh" ]; then bash "$ACTION_DIR/scripts/tau_verify.sh"; fi
        if [ -x "$ACTION_DIR/scripts/spec_guard.sh" ]; then bash "$ACTION_DIR/scripts/spec_guard.sh" || true; fi
        if [ -s ".tau_ledger/signals/observable.tsv" ] && [ -x "$ACTION_DIR/scripts/tau_adapter.sh" ]; then
          bash "$ACTION_DIR/scripts/tau_adapter.sh" .tau_ledger/signals/observable.tsv || true
        fi

    - name: Record wrapper digest
      shell: bash
      env:
        ACTION_DIR: ${{ github.action_path }}
      working-directory: ${{ inputs.working-directory }}
      run: |
        set +H; umask 022
        mkdir -p .tau_ledger
        bash "$ACTION_DIR/scripts/bin/hash_action_wrapper.sh" "${{ inputs.working-directory }}"

    - name: Enforce wrapper digest (required)
      shell: bash
      env:
        ACTION_DIR: ${{ github.action_path }}
      working-directory: ${{ inputs.working-directory }}
      run: |
        set -Eeuo pipefail; set +H; umask 022
        bash "$ACTION_DIR/scripts/bin/enforce_wrapper_digest.sh" "${{ inputs.working-directory }}"

    - name: Collect outputs
      id: outs
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        set -Eeuo pipefail; set +H; umask 022
        rcpt=""; head=""; root=""
        if [ -f .tau_ledger/CHAIN ]; then
          rcpt=$(awk '{print $2}' .tau_ledger/CHAIN | tail -n1 || true)
          head=$(awk '{print $1}' .tau_ledger/CHAIN | tail -n1 || true)
        fi
        [ -z "$rcpt" ] && rcpt=$(ls -1t .tau_ledger/*.json 2>/dev/null | head -n1 || true)
        if [ -f tau-crystal-manifest.json ]; then
          root=$(grep -oE '"merkle_root"[[:space:]]*:[[:space:]]*"[^"]*"' tau-crystal-manifest.json \
                 | sed -E 's/.*:"([^"]*)".*/\1/' | head -n1 || true)
        fi
        echo "receipt=$rcpt" >> "$GITHUB_OUTPUT"
        echo "head=$head"     >> "$GITHUB_OUTPUT"
        echo "root=$root"     >> "$GITHUB_OUTPUT"
